In [1]:
import numpy as np
import copy
import math
import random

In [2]:
def initial_state():
    return [[0,0,0,0,0,0,0], [0,0,0,0,0,0,0], 
        [0,0,0,0,0,0,0], [0,0,0,0,0,0,0], 
        [0,0,0,0,0,0,0], [0,0,0,0,0,0,0]]

In [3]:
grid = initial_state()
print(np.matrix(grid))

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [4]:
def tie(grid): 
    for i in range(6):
        for j in range(7):
            if grid[i][j] == 0:
                return False
    return True

In [5]:
tie(grid)

False

In [6]:
grid[0:4]

[[0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0]]

In [7]:
def winner(grid):
    #Checking rows:
    for i in range(6):
        for j in range(4):
            if grid[i][j:j+4] == ["R","R","R","R"]:
                return "R"
            if grid[i][j:j+4] == ["Y","Y","Y","Y"]:
                return "Y"

    #Checking Columns:
    for j in range(3):
        g = grid[j:j+4]
        for q in range(7):
            vals = [x[q] for x in g]
            if vals == ["R","R","R","R"]:
                return "R"
            if vals == ["Y","Y","Y","Y"]:
                return "Y"

    #Checking Diagonals:
    #Checking for R
    for i in range(6):
        for j in range(7):
            if grid[i][j] == "R":
                try:
                    if grid[i-3][j-3] == "R" and i-3 >= 0 and j-3 >= 0 and grid[i-2][j-2] == "R" and grid[i-1][j-1] == "R":
                        return "R"
                except: pass
                try:
                    if grid[i-3][j+3] == "R" and i-3 >= 0 and grid[i-2][j+2] == "R" and grid [i-1][j+1] == "R":
                        return "R"
                except: pass
    #Checking for Y
    for i in range(6):
        for j in range(7):
            if grid[i][j] == "Y":
                try:
                    if grid[i-3][j-3] == "Y" and i-3 >= 0 and j-3 >= 0 and grid[i-2][j-2] == "Y" and grid[i-1][j-1] == "Y":
                        return "Y"
                except: pass
                try:
                    if grid[i-3][j+3] == "Y" and i-3 >= 0 and grid[i-2][j+2] == "Y" and grid [i-1][j+1] == "Y":
                        return "Y"
                except: pass
    return False

In [8]:
winner(grid)

False

In [9]:
def three_check(grid):
    y_check = False
    r_check = False
    #Checking rows:
    for i in range(6):
        for j in range(4):
            if grid[i][j:j+4] == [0,"R","R","R"] or grid[i][j:j+4] == ["R","R","R",0]:
                r_check = True
            if grid[i][j:j+4] == [0,"Y","Y","Y"] or grid[i][j:j+4] == ["Y","Y","Y",0]:
                y_check = True
            if grid[i][j:j+4] == ["R",0,"R","R"] or grid[i][j:j+4] == ["R","R",0,"R"]:
                r_check = True
            if grid[i][j:j+4] == ["Y",0,"Y","Y"] or grid[i][j:j+4] == ["Y","Y",0,"Y"]:
                y_check = True

    #Checking Columns:
    for j in range(3):
        g = grid[j:j+4]
        for q in range(7):
            vals = [x[q] for x in g]
            if vals == [0, "R","R","R"]:
                r_check = True
            if vals == [0, "Y","Y","Y"]:
                y_check = True
            
    
    #Checking Diagonals:
    for i in range(6):
        for j in range(7):
            #Checking for R
            if grid[i][j] == "R":
                try:
                    if grid[i-3][j-3] == 0 and i-3 >= 0 and j-3 >= 0 and grid[i-2][j-2] == "R" and grid[i-1][j-1] == "R":
                        r_check = True
                except: pass
                try:
                    if grid[i-3][j+3] == 0 and i-3 >= 0 and grid[i-2][j+2] == "R" and grid [i-1][j+1] == "R":
                        r_check = True
                except: pass
                try:
                    if grid[i-3][j-3] == "R" and i-3 >= 0 and j-3 >= 0 and grid[i-2][j-2] == 0 and grid[i-1][j-1] == "R":
                        r_check = True
                except: pass
                try:
                    if grid[i-3][j+3] == "R" and i-3 >= 0 and grid[i-2][j+2] == 0 and grid [i-1][j+1] == "R":
                        r_check = True
                except: pass
                try:
                    if grid[i-3][j-3] == "R" and i-3 >= 0 and j-3 >= 0 and grid[i-2][j-2] == "R" and grid[i-1][j-1] == 0:
                        r_check = True
                except: pass
                try:
                    if grid[i-3][j+3] == "R" and i-3 >= 0 and grid[i-2][j+2] == "R" and grid [i-1][j+1] == 0:
                        r_check = True
                except: pass
                    
            #Checking for Y
            elif grid[i][j] == "Y":
                try:
                    if grid[i-3][j-3] == 0 and i-3 >= 0 and j-3 >= 0 and grid[i-2][j-2] == "Y" and grid[i-1][j-1] == "Y":
                        y_check = True
                except: pass
                try:
                    if grid[i-3][j+3] == 0 and i-3 >= 0 and grid[i-2][j+2] == "Y" and grid [i-1][j+1] == "Y":
                        y_check = True
                except: pass
                try:
                    if grid[i-3][j-3] == "Y" and i-3 >= 0 and j-3 >= 0 and grid[i-2][j-2] == 0 and grid[i-1][j-1] == "Y":
                        y_check = True
                except: pass
                try:
                    if grid[i-3][j+3] == "Y" and i-3 >= 0 and grid[i-2][j+2] == 0 and grid [i-1][j+1] == "Y":
                        y_check = True
                except: pass
                try:
                    if grid[i-3][j-3] == "Y" and i-3 >= 0 and j-3 >= 0 and grid[i-2][j-2] == "Y" and grid[i-1][j-1] == 0:
                        y_check = True
                except: pass
                try:
                    if grid[i-3][j+3] == "Y" and i-3 >= 0 and grid[i-2][j+2] == "Y" and grid [i-1][j+1] == 0:
                        y_check = True
                except: pass
                
    if y_check and r_check:
        return True
    elif y_check:
        return "Y"
    elif r_check:
        return "R"
    else:
        return False

In [10]:
three_check(grid)

False

In [11]:
grid

[[0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0]]

In [12]:
def trap(grid):
    y_check = False
    r_check = False
    for i in range(6):
        for j in range(7):
            #Checking for R
            if grid[i][j] == "R":
                try:
                    if grid[i][j+1] == 0 and grid[i][j+2] == "R" and grid[i][j+3] == "R" and grid[i+1][j+1] == 0 and grid[i+2][j+2] == "R" and grid[i+3][j+3] == "R":
                        r_check = True
                except: pass
                try:
                    if grid[i-1][j+1] == 0 and i-1 >= 0 and grid[i-2][j+2] == "R" and i-2 >= 0 and grid[i-3][j+3] == "R" and i-3 >= 0 and grid[i][j+1] == 0 and grid[i][j+2] == "R" and grid[i][j+3] == "R":
                        r_check = True
                except: pass
                try:
                    if grid[i][j+1] == "R" and grid[i][j+2] == 0 and grid[i][j+3] == "R" and grid[i+1][j+2] == 0 and grid[i+2][j+3] == "R" and grid[i+3][j+4] == "R":
                        r_check = True
                except: pass
                try:
                    if grid[i][j+1] == "R" and grid[i][j+2] == 0 and grid[i][j+3] == "R" and grid[i-1][j+2] == 0 and i-1 >= 0 and grid[i-2][j+3] == "R" and i-2 >= 0 and grid[i-3][j+4] == "R" and i-3 >= 0:
                        r_check = True
                except: pass
                try:
                    if grid[i+1][j+1] == "R" and grid[i+1][j+2] == 0 and grid[i+1][j+3] == "R" and grid[i+1][j+4] == "R" and grid[i+2][j+2] == 0 and grid[i+3][j+3] == "R":
                        r_check = True
                except: pass
                try:
                    if grid[i-1][j+1] == "R" and grid[i-1][j+2] == 0 and grid[i-1][j+3] == "R" and grid[i-1][j+4] == "R" and grid[i-2][j+2] == 0 and grid[i-3][j+3] == "R" and i-3 >= 0:
                        r_check = True
                except: pass
                try:
                    if grid[i+1][j] == "R" and grid[i+1][j+1] == "R" and grid[i+1][j+2] == 0 and grid[i+1][j+3] == "R" and grid[i+2][j+2] == 0 and grid[i+3][j+3] == "R":
                        r_check = True
                except: pass
                try:
                    if grid[i-1][j] == "R" and grid[i-1][j+1] == "R" and grid[i-1][j+2] == 0 and grid[i-1][j+3] == "R" and grid[i-2][j+2] == 0 and grid[i-3][j+3] == "R" and i-3 >= 0:
                        r_check = True
                except: pass
                try:
                    if grid[i][j+1] == "R" and grid[i][j+2] == 0 and grid[i][j+3] == "R" and grid[i+1][j+2] == 0 and grid[i+2][j+1] == "R" and grid[i+3][j] == "R":
                        r_check = True
                except: pass
                try:
                    if grid[i+1][j+1] == "R" and grid[i+2][j+2] == 0 and grid[i+3][j+3] == "R" and grid[i+3][j] == "R" and grid[i+3][j+1] == "R" and grid[i+3][j+2] == 0:
                        r_check = True
                except: pass
                try:
                    if grid[i][j+1] == 0 and grid[i][j+2] == "R" and grid[i][j+3] == "R" and grid[i+1][j+1] == 0 and grid[i+2][j] == "R" and grid[i+3][j-1] == "R" and j-1 >= 0:
                        r_check = True
                except: pass
                try:
                    if grid[i+1][j+1] == "R" and grid[i+2][j+2] == 0 and grid[i+3][j+1] == "R" and grid[i+3][j+2] == 0 and grid[i+3][j+3] == "R" and grid[i+3][j+4] == "R":
                        r_check = True
                except: pass
                try:
                    if grid[i][j+1] == "R" and grid[i][j+2] == 0 and grid[i][j+3] == "R" and grid[i-1][j+4] == "R" and i-1 >= 0 and grid[i+1][j+2] == 0 and grid[i+2][j+1] == "R":
                        r_check = True
                except: pass
                try:
                    if grid[i][j+1] == "R" and grid[i][j+2] == 0 and grid[i][j+3] == "R" and grid[i-2][j+1] == "R" and i-2 >= 0 and grid[i-1][j+2] == 0 and grid[i+1][j+4] == "R":
                        r_check = True
                except: pass
                try:
                    if grid[i][j+1] == 0 and grid[i][j+2] == "R" and grid[i][j+3] == "R" and grid[i-1][j+3] == "R" and i-1 >= 0 and grid[i+1][j+1] == 0 and grid[i+2][j] == "R":
                        r_check = True
                except: pass
                try:
                    if grid[i+1][j+1] == 0 and grid[i+2][j] == "R" and grid[i+2][j+1] == 0 and grid[i+2][j+2] == "R" and grid[i+2][j+3] == "R" and grid[i+3][j+3] == "R":
                        r_check = True
                except: pass
                try:
                    if grid[i][j-1] == 0 and j-1 >= 0 and grid[i][j+1] == "R" and grid[i][j+2] == "R" and grid[i+1][j+1] == "R" and grid[i+2][j+2] == "R" and grid[i-1][j-1] == 0 and i-1 >= 0:
                        r_check = True
                except: pass
                try:
                    if grid[i][j+1] == "R" and grid[i][j+2] == "R" and grid[i][j+3] == 0 and grid[i+1][j+1] == "R" and grid[i+2][j] == "R" and grid[i-1][j+3] == 0 and i-1 >= 0:
                        r_check = True
                except: pass
                try:
                    if grid[i][j-1] == 0 and j-1 >= 0 and grid[i+1][j-1] == 0 and grid[i][j+1] == "R" and grid[i][j+2] == "R" and grid[i-1][j+1] == "R" and grid[i-2][j+2] == "R" and i-2 >= 0:
                        r_check = True
                except: pass
                try:
                    if grid[i-2][j] == "R" and i-2 >= 0 and grid[i-1][j+1] == "R" and grid[i][j+1] == "R" and grid[i][j+2] == "R" and grid[i][j+3] == 0 and grid[i+1][j+3] == 0:
                        r_check = True
                except: pass
                
            #Checking for Y
            elif grid[i][j] == "Y":
                try:
                    if grid[i][j+1] == 0 and grid[i][j+2] == "Y" and grid[i][j+3] == "Y" and grid[i+1][j+1] == 0 and grid[i+2][j+2] == "Y" and grid[i+3][j+3] == "Y":
                        y_check = True
                except: pass
                try:
                    if grid[i-1][j+1] == 0 and i-1 >= 0 and grid[i-2][j+2] == "Y" and i-2 >= 0 and grid[i-3][j+3] == "Y" and i-3 >= 0 and grid[i][j+1] == 0 and grid[i][j+2] == "Y" and grid[i][j+3] == "Y":
                        y_check = True
                except: pass
                try:
                    if grid[i][j+1] == "Y" and grid[i][j+2] == 0 and grid[i][j+3] == "Y" and grid[i+1][j+2] == 0 and grid[i+2][j+3] == "Y" and grid[i+3][j+4] == "Y":
                        y_check = True
                except: pass
                try:
                    if grid[i][j+1] == "Y" and grid[i][j+2] == 0 and grid[i][j+3] == "Y" and grid[i-1][j+2] == 0 and i-1 >= 0 and grid[i-2][j+3] == "Y" and i-2 >= 0 and grid[i-3][j+4] == "Y" and i-3 >= 0:
                        y_check = True
                except: pass
                try:
                    if grid[i+1][j+1] == "Y" and grid[i+1][j+2] == 0 and grid[i+1][j+3] == "Y" and grid[i+1][j+4] == "Y" and grid[i+2][j+2] == 0 and grid[i+3][j+3] == "Y":
                        y_check = True
                except: pass
                try:
                    if grid[i-1][j+1] == "Y" and grid[i-1][j+2] == 0 and grid[i-1][j+3] == "Y" and grid[i-1][j+4] == "Y" and grid[i-2][j+2] == 0 and grid[i-3][j+3] == "Y" and i-3 >= 0:
                        y_check = True
                except: pass
                try:
                    if grid[i+1][j] == "Y" and grid[i+1][j+1] == "Y" and grid[i+1][j+2] == 0 and grid[i+1][j+3] == "Y" and grid[i+2][j+2] == 0 and grid[i+3][j+3] == "Y":
                        y_check = True
                except: pass
                try:
                    if grid[i-1][j] == "Y" and grid[i-1][j+1] == "Y" and grid[i-1][j+2] == 0 and grid[i-1][j+3] == "Y" and grid[i-2][j+2] == 0 and grid[i-3][j+3] == "Y" and i-3 >= 0:
                        y_check = True
                except: pass
                try:
                    if grid[i][j+1] == "Y" and grid[i][j+2] == 0 and grid[i][j+3] == "Y" and grid[i+1][j+2] == 0 and grid[i+2][j+1] == "Y" and grid[i+3][j] == "Y":
                        y_check = True
                except: pass
                try:
                    if grid[i+1][j+1] == "Y" and grid[i+2][j+2] == 0 and grid[i+3][j+3] == "Y" and grid[i+3][j] == "Y" and grid[i+3][j+1] == "Y" and grid[i+3][j+2] == 0:
                        y_check = True
                except: pass
                try:
                    if grid[i][j+1] == 0 and grid[i][j+2] == "Y" and grid[i][j+3] == "Y" and grid[i+1][j+1] == 0 and grid[i+2][j] == "Y" and grid[i+3][j-1] == "Y" and j-1 >= 0:
                        y_check = True
                except: pass
                try:
                    if grid[i+1][j+1] == "Y" and grid[i+2][j+2] == 0 and grid[i+3][j+1] == "Y" and grid[i+3][j+2] == 0 and grid[i+3][j+3] == "Y" and grid[i+3][j+4] == "Y":
                        y_check = True
                except: pass
                try:
                    if grid[i][j+1] == "Y" and grid[i][j+2] == 0 and grid[i][j+3] == "Y" and grid[i-1][j+4] == "Y" and i-1 >= 0 and grid[i+1][j+2] == 0 and grid[i+2][j+1] == "Y":
                        y_check = True
                except: pass
                try:
                    if grid[i][j+1] == "Y" and grid[i][j+2] == 0 and grid[i][j+3] == "Y" and grid[i-2][j+1] == "Y" and i-2 >= 0 and grid[i-1][j+2] == 0 and grid[i+1][j+4] == "Y":
                        y_check = True
                except: pass
                try:
                    if grid[i][j+1] == 0 and grid[i][j+2] == "Y" and grid[i][j+3] == "Y" and grid[i-1][j+3] == "Y" and i-1 >= 0 and grid[i+1][j+1] == 0 and grid[i+2][j] == "Y":
                        y_check = True
                except: pass
                try:
                    if grid[i+1][j+1] == 0 and grid[i+2][j] == "Y" and grid[i+2][j+1] == 0 and grid[i+2][j+2] == "Y" and grid[i+2][j+3] == "Y" and grid[i+3][j+3] == "Y":
                        y_check = True
                except: pass
                try:
                    if grid[i][j-1] == 0 and j-1 >= 0 and grid[i][j+1] == "Y" and grid[i][j+2] == "Y" and grid[i+1][j+1] == "Y" and grid[i+2][j+2] == "Y" and grid[i-1][j-1] == 0 and i-1 >= 0:
                        y_check = True
                except: pass
                try:
                    if grid[i][j+1] == "Y" and grid[i][j+2] == "Y" and grid[i][j+3] == 0 and grid[i+1][j+1] == "Y" and grid[i+2][j] == "Y" and grid[i-1][j+3] == 0 and i-1 >= 0:
                        y_check = True
                except: pass
                try:
                    if grid[i][j-1] == 0 and j-1 >= 0 and grid[i+1][j-1] == 0 and grid[i][j+1] == "Y" and grid[i][j+2] == "Y" and grid[i-1][j+1] == "Y" and grid[i-2][j+2] == "Y" and i-2 >= 0:
                        y_check = True
                except: pass
                try:
                    if grid[i-2][j] == "Y" and i-2 >= 0 and grid[i-1][j+1] == "Y" and grid[i][j+1] == "Y" and grid[i][j+2] == "Y" and grid[i][j+3] == 0 and grid[i+1][j+3] == 0:
                        y_check = True
                except: pass
    
    if y_check and r_check:
        return True
    elif y_check:
        return "Y"
    elif r_check:
        return "R"
    else:
        return False

In [13]:
grid = initial_state()

In [14]:
print(np.matrix(grid))

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [15]:
trap(grid)

False

In [16]:
def actions(grid):
    moves = []
    for i in range(7):
        row = 5
        while grid[row][i] != 0 and row >= 0:
            row -= 1
        if grid[row][i] == 0:
            moves.append([row,i])
    random.shuffle(moves)
    return moves

In [17]:
actions(grid)

[[5, 0], [5, 6], [5, 4], [5, 2], [5, 1], [5, 5], [5, 3]]

In [18]:
def terminal(grid):
    if tie(grid) or winner(grid):
        return True
    return False

In [19]:
terminal(grid)

False

In [20]:
def player(grid):
    #Red goes first
    red_count = 0
    yellow_count = 0
    for i in range(6):
        for j in range(7):
            if grid[i][j] == "R":
                red_count += 1
            elif grid[i][j] == "Y":
                yellow_count += 1

    if red_count == yellow_count:
        return "R"
    else:
        return "Y"

In [21]:
player(grid)

'R'

In [22]:
def result(grid, move):
    c = copy.deepcopy(grid)
    y = move[0]
    x = move[1]
    mark = player(grid)
    c[y][x] = mark
    return c

In [23]:
print(np.matrix(result(grid, [5,0])))

[['0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0']
 ['R' '0' '0' '0' '0' '0' '0']]


In [24]:
print(np.matrix(grid))

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [25]:
def utility(grid):
    if winner(grid) == "R":
        return 1
    elif winner(grid) == "Y":
        return -1
    elif trap(grid) == "R":
        return 0.9
    elif trap(grid) == "Y":
        return -0.9
    elif trap(grid) == True:
        if player(grid) == "R":
            return 0.6
        else:
            return -0.6
    elif three_check(grid) == "R":
        return 0.5
    elif three_check(grid) == "Y":
        return -0.5
    elif three_check(grid) == True:
        if player(grid) == "R":
            return 0.25
        else:
            return -0.25
    else:
        return 0

In [26]:
utility(grid)

0

In [27]:
def Max_value(grid):
    if terminal(grid):
        return utility(grid)

    v = -math.inf
    for a in actions(grid):
        v = max(v, Min_value(result(grid, a)))

    return v

In [28]:
def Min_value(grid):
    if terminal(grid):
        return utility(grid)

    v = math.inf
    for a in actions(grid):
        v = min(v, Max_value(result(grid, a)))

    return v

In [29]:
def minimax(grid):
    if terminal(grid) == True:
        return None
    p = player(grid)

    if p == "R":
        reward = -1*math.inf
        for a in actions(grid):
            v = Min_value(result(grid, a))
            if v > reward:
                reward = v
                move = a
        return move

    elif p == "Y":
        reward = math.inf
        for a in actions(grid):
            v = Max_value(result(grid, a))
            if v < reward:
                reward = v
                move = a
        return move

In [30]:
def Max_value_depth(grid, depth):
    if terminal(grid) or depth == 0:
        return utility(grid)

    v = -math.inf
    for a in actions(grid):
        v = max(v, Min_value_depth(result(grid, a), depth-1))

    return v

In [31]:
def Min_value_depth(grid, depth):
    if terminal(grid) or depth == 0:
        return utility(grid)

    v = math.inf
    for a in actions(grid):
        v = min(v, Max_value_depth(result(grid, a), depth-1))

    return v

In [32]:
def minimax_depth_revised(grid, depth):
    if terminal(grid) == True or depth == 0:
        return utility(grid)
    p = player(grid)

    if p == "R":
        reward = -1*math.inf
        for a in actions(grid):
            v = Min_value_depth(result(grid, a), depth-1)
            print(f"R {v}")
            if v > reward:
                reward = v
                move = a
        return move

    elif p == "Y":
        reward = math.inf
        for a in actions(grid):
            v = Max_value_depth(result(grid, a), depth-1)
            print(f"Y {v}")
            if v < reward:
                reward = v
                move = a
        return move

In [33]:
print(np.matrix(grid))

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [34]:
def choose_player():
    print("Red goes first & yellow goes second...")
    pick = input("Do you want to play as red or yellow? (Type r or y): ")
    print("\n")
    if pick.lower() == "r":
        return "R"
    else:
        return "Y"

In [35]:
def ai_move():
    global grid
    p = player(grid)
    print(f"\nIt is {p}‘s Turn.")
    print(np.matrix(grid))
    print("\nAI Thinking...")
    choice = minimax(grid)
    y = choice[0]
    x = choice[1]
    grid[y][x] = p

In [36]:
def ai_move_depth_revised(depth):
    global grid
    p = player(grid)
    choice = [8,7]
    print(f"\nIt Is The AI‘s Turn.")
    print(np.matrix(grid))
    print("\nAI Thinking...")
    choice = minimax_depth_revised(grid, depth)
    y = choice[0]
    x = choice[1]
    print(f"AI chose column {x+1}.")
    grid[y][x] = p

In [37]:
def human_move():
    global grid
    p = player(grid)
    print(f"\nIt Is Your Turn.")
    print(np.matrix(grid))
    col = int(input("Enter the column number (1-7): "))
    print(f"You chose column {col}.")
    col -= 1
    m = actions(grid)
    for move in m:
        if move[1] == col:
            y = move[0]
            x = move[1]
            grid[y][x] = p

In [38]:
def play():
    global grid
    grid = initial_state()
    human = choose_player()
    diff = 5
    while terminal(grid) == False:
        if player(grid) == human:
            human_move()
        else:
            ai_move_depth_revised(diff+1)
    w = winner(grid)
    print(np.matrix(grid))
    grid = initial_state()
    if human == w:
        print("\nHuman Wins!")
    elif w == False:
        print("\nTie!")
    else:
        print("\nAI Wins!")

In [39]:
play()

Red goes first & yellow goes second...
Do you want to play as red or yellow? (Type r or y): y



It Is The AI‘s Turn.
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]

AI Thinking...
R 0
R 0
R 0
R 0
R 0
R 0
R 0
AI chose column 2.

It Is Your Turn.
[['0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0']
 ['0' 'R' '0' '0' '0' '0' '0']]
Enter the column number (1-7): 4
You chose column 4.

It Is The AI‘s Turn.
[['0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0']
 ['0' 'R' '0' 'Y' '0' '0' '0']]

AI Thinking...
R 0
R 0
R 0
R 0
R 0
R 0
R 0
AI chose column 4.

It Is Your Turn.
[['0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' 'R' '0' '0' '0']
 ['0' 'R' '0'