In [155]:
import numpy as np
grid = []
s = []
f = []
current = []

In [135]:
def initial_size(n):
    global grid
    grid = []
    for i in range(n):
        grid.append([0]*n)

In [136]:
initial_size(10)

In [137]:
def blocked(n):
    global grid
    blocked = []
    for i in range(n):
        point = input("Enter blocked coordinate, separated by a space (ex: 4 5): ")
        y = int(point.split()[0])
        x = int(point.split()[1])
        blocked.append([y,x])
        
    for point in blocked:
        y = point[0]
        x = point[1]
        if y != 0:
            y -= 1
        if x != 0:
            x -= 1
        grid[y][x] = "#"
    print("\n")
    print(np.matrix(grid))

In [10]:
blocked(4)

Enter blocked coordinate, separated by a space (ex: 4 5): 1 1
Enter blocked coordinate, separated by a space (ex: 4 5): 7 7
Enter blocked coordinate, separated by a space (ex: 4 5): 3 5
Enter blocked coordinate, separated by a space (ex: 4 5): 3 4


[['#' '0' '#' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '#' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '#' '#' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '#' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']]


In [138]:
def start():
    global grid
    global s
    global current
    print(np.matrix(grid))
    print("\n")
    s = input("Enter the start coordinate (Ex: 3 4): ")
    y = int(s.split()[0])
    x = int(s.split()[1])
    if y != 0:
        y -= 1
    if x != 0:
        x -= 1
    grid[y][x] = "S"
    s = [y,x]
    current = [y,x]
    print("\n")
    print(np.matrix(grid))

In [16]:
start()

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


Enter the start coordinate (Ex: 3 4): 1 1


[['S' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']]


In [139]:
def finish():
    global grid
    global f
    s = input("Enter the finish coordinate (Ex: 3 4): ")
    y = int(s.split()[0])
    x = int(s.split()[1])
    if y != 0:
        y -= 1
    if x != 0:
        x -= 1
    grid[y][x] = "F"
    f = [y,x]
    print("\n")
    print(np.matrix(grid))

In [18]:
finish()

[['S' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']]


Enter the finish coordinate (Ex: 3 4): 10 10


[['S' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' 'F']]


In [140]:
def make_grid():
    initial_size(10)
    start()
    finish()
    b = int(input("How many blocked coordinates are there: "))
    blocked(b)

In [169]:
make_grid()

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


Enter the start coordinate (Ex: 3 4): 1 2


[['0' 'S' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']]
Enter the finish coordinate (Ex: 3 4): 10 8


[['0' 'S' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '

In [60]:
def euclidean_heuristic(position,final):
    y1 = position[0]
    x1 = position[1]
    y2 = final[0]
    x2 = final[1]
    a = (x2-x1)**2
    b = (y2-y1)**2
    c = round((a + b)**0.5,3)
    return c

In [73]:
euclidean_heuristic([1,4],[2,2])

2.236

In [68]:
def basic_heuristic(position,final):
    y1 = position[0]
    x1 = position[1]
    y2 = final[0]
    x2 = final[1]
    a = abs(y2-y1)
    b = abs(x2-x1)
    return a + b

In [72]:
basic_heuristic([1,4],[2,2])

3

In [156]:
def adjacent_basic(position):
    global grid
    global f
    y = position[0]
    x = position[1]
    moves = []
    heuristic = []
    final = []
    
    #Checking up, down, left, right
    try:
        if (grid[y-1][x] == 0 or grid[y-1][x] == "F") and y-1 >= 0 and x >= 0:
            moves.append([y-1,x,0])
    except: pass
    try:
        if (grid[y+1][x] == 0 or grid[y+1][x] == "F") and y+1 >= 0 and x >= 0:
            moves.append([y+1,x,0])
    except: pass
    try:
        if (grid[y][x-1] == 0 or grid[y][x-1] == "F") and y >= 0 and x-1 >= 0:
            moves.append([y,x-1,0])
    except: pass
    try:
        if (grid[y][x+1] == 0 or grid[y][x+1] == "F") and y >= 0 and x+1 >= 0:
            moves.append([y,x+1,0])
    except: pass
    
    #Checking diagonals
    try:
        if (grid[y-1][x-1] == 0 or grid[y-1][x-1] == "F") and y-1 >= 0 and x-1 >= 0:
            moves.append([y-1,x-1,1])
    except: pass
    try:
        if (grid[y-1][x+1] == 0 or grid[y-1][x+1] == "F") and y-1 >= 0 and x+1 >= 0:
            moves.append([y-1,x+1,1])
    except: pass
    try:
        if (grid[y+1][x-1] == 0 or grid[y+1][x-1] == "F") and y+1 >= 0 and x-1 >= 0:
            moves.append([y+1,x-1,1])
    except: pass
    try:
        if (grid[y+1][x+1] == 0 or grid[y+1][x+1] == "F") and y+1 >= 0 and x+1 >= 0:
            moves.append([y+1,x+1,1])
    except: pass
    
    #Basic Heuristic
    for move in moves:
        y = move[0]
        x = move[1]
        z = bool(move[2])
        h = basic_heuristic([y,x],f)
        if z:
            h += 0.5
        heuristic.append(h)
    
    for i in range(len(moves)):
        index = heuristic.index(min(heuristic))
        final.append(moves[index])
        del heuristic[index]
        del moves[index]
    
    return final

In [157]:
def adjacent_euclidean(position):
    global grid
    global f
    y = position[0]
    x = position[1]
    moves = []
    heuristic = []
    final = []
    
    #Checking up, down, left, right
    try:
        if (grid[y-1][x] == 0 or grid[y-1][x] == "F") and y-1 >= 0 and x >= 0:
            moves.append([y-1,x,0])
    except: pass
    try:
        if (grid[y+1][x] == 0 or grid[y+1][x] == "F") and y+1 >= 0 and x >= 0:
            moves.append([y+1,x,0])
    except: pass
    try:
        if (grid[y][x-1] == 0 or grid[y][x-1] == "F") and y >= 0 and x-1 >= 0:
            moves.append([y,x-1,0])
    except: pass
    try:
        if (grid[y][x+1] == 0 or grid[y][x+1] == "F") and y >= 0 and x+1 >= 0:
            moves.append([y,x+1,0])
    except: pass
    
    #Checking diagonals
    try:
        if (grid[y-1][x-1] == 0 or grid[y-1][x-1] == "F") and y-1 >= 0 and x-1 >= 0:
            moves.append([y-1,x-1,1])
    except: pass
    try:
        if (grid[y-1][x+1] == 0 or grid[y-1][x+1] == "F") and y-1 >= 0 and x+1 >= 0:
            moves.append([y-1,x+1,1])
    except: pass
    try:
        if (grid[y+1][x-1] == 0 or grid[y+1][x-1] == "F") and y+1 >= 0 and x-1 >= 0:
            moves.append([y+1,x-1,1])
    except: pass
    try:
        if (grid[y+1][x+1] == 0 or grid[y+1][x+1] == "F") and y+1 >= 0 and x+1 >= 0:
            moves.append([y+1,x+1,1])
    except: pass
    
    #Euclidean Heuristic
    for move in moves:
        y = move[0]
        x = move[1]
        z = bool(move[2])
        h = euclidean_heuristic([y,x],f)
        if z:
            h += 0.5
        heuristic.append(h)
    
    for i in range(len(moves)):
        index = heuristic.index(min(heuristic))
        final.append(moves[index])
        del heuristic[index]
        del moves[index]
    
    return final

In [158]:
print(np.matrix(grid))

[]


In [82]:
adjacent(s)

[[1, 1, 1], [0, 1, 0], [1, 0, 0]]

In [132]:
def make_move(position, euclidean = True):
    global grid
    global f
    if euclidean:
        moves = adjacent_euclidean(position)
    else:
        moves = adjacent_basic(position)
    y = moves[0][0]
    x = moves[0][1]
    if [y,x] != f:
        grid[y][x] = "*"
        print("\n")
        print(np.matrix(grid))
    else:
        print("\nSuccess! Reached the final destination.")
    return [y,x]

In [145]:
def solve(euclid=True):
    global grid
    global s
    global f
    global current
    while current != f:
        #True = euclidean heuristic
        #False = basic heuristic
        current = make_move(current,euclid)

In [170]:
solve(True)



[['0' 'S' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '*' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '#' '0' '0']
 ['0' '0' '0' '0' '0' '0' '#' '#' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '#' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' 'F' '0' '0']]


[['0' 'S' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '*' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '*' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '#' '0' '0']
 ['0' '0' '0' '0' '0' '0' '#' '#' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '#' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' 'F' '0' '0']]


[['0' 'S' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '*' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '*' '0' '0' '0' '0' '0' '0']
 ['

In [171]:
def clear_moves_made():
    global grid
    global current
    global s
    for i in range(10):
        for j in range(10):
            if grid[i][j] == "*":
                grid[i][j] = 0
    current = s
    print(np.matrix(grid))

In [172]:
clear_moves_made()

[['0' 'S' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '#' '0' '0']
 ['0' '0' '0' '0' '0' '0' '#' '#' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '#' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' 'F' '0' '0']]


In [173]:
solve(False)



[['0' 'S' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '*' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '#' '0' '0']
 ['0' '0' '0' '0' '0' '0' '#' '#' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '#' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' 'F' '0' '0']]


[['0' 'S' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '*' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '*' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '#' '0' '0']
 ['0' '0' '0' '0' '0' '0' '#' '#' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' '#' '0' '0']
 ['0' '0' '0' '0' '0' '0' '0' 'F' '0' '0']]


[['0' 'S' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '*' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '0' '*' '0' '0' '0' '0' '0' '0']
 ['