In [ ]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
# Importing the dataset
dataset = pd.read_csv('Sheet-Classification.csv')
X = dataset.iloc[:, [2,3,4,6,7,8,9,10,11]].values
y = dataset.iloc[:, 12].values

In [ ]:
X[0]

array([  1. ,  30. ,  15. ,  19. ,  83. ,  40. ,  28. ,   2.4, 147. ])

In [ ]:
y[0]

1

In [ ]:
print(X[:10])

[[  1.   30.   15.   19.   83.   40.   28.    2.4 147. ]
 [ 10.  225.   10.    7.   98.   43.    3.    2.6 129. ]
 [  5.  225.    2.   11.   89.   25.    0.    0.8 379. ]
 [ 10.  150.    4.    6.   98.   66.   11.    1.4  64. ]
 [  5.   24.   10.   33.   91.  105.   11.    2.6 376. ]
 [ 15.  200.    1.   27.   87.    8.    6.    1.3  71. ]
 [ 10.   20.    1.    8.   91.   57.   29.    1.7  24. ]
 [  3.   35.    7.   15.   92.   13.   27.    2.   25. ]
 [  5.    5.    8.   20.   92.   16.   38.    1.  300. ]
 [ 20.   65.    4.   12.   98.   21.    0.    1.4 120. ]]


In [ ]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
# Fitting Decision Tree Classification to the Training set
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [ ]:
# Fitting Kernel SVM to the Training set
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [ ]:
# Fitting K-NN to the Training set
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [ ]:
# Fitting Random Forest Classification to the Training set
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [ ]:
# Fitting Naive Bayes to the Training set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [ ]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
np.set_printoptions(precision=2)
number_of_tests = 9
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1)[:number_of_tests])

[[1 1]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [0 0]]


In [ ]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[2 0]
 [2 5]]


In [ ]:
#print(classifier.predict(sc.transform([[FG, EG, QF, WEEKS, RS, IR, ROE, U/D, VOL]])))
print(classifier.predict(sc.transform([[ 15, 100, 8,   10,  97, 13, 29,  1.7, 106]])))

[1]


In [ ]:
# Building the optimal model using Backward Elimination
import statsmodels.api as sm

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [ ]:
X = np.append(arr = np.ones((len(X), 1)).astype(int), values = X, axis = 1)

In [ ]:
X[:10]

array([[  1. ,   1. ,  30. ,  15. ,  19. ,  83. ,  40. ,  28. ,   2.4,
        147. ],
       [  1. ,  10. , 225. ,  10. ,   7. ,  98. ,  43. ,   3. ,   2.6,
        129. ],
       [  1. ,   5. , 225. ,   2. ,  11. ,  89. ,  25. ,   0. ,   0.8,
        379. ],
       [  1. ,  10. , 150. ,   4. ,   6. ,  98. ,  66. ,  11. ,   1.4,
         64. ],
       [  1. ,   5. ,  24. ,  10. ,  33. ,  91. , 105. ,  11. ,   2.6,
        376. ],
       [  1. ,  15. , 200. ,   1. ,  27. ,  87. ,   8. ,   6. ,   1.3,
         71. ],
       [  1. ,  10. ,  20. ,   1. ,   8. ,  91. ,  57. ,  29. ,   1.7,
         24. ],
       [  1. ,   3. ,  35. ,   7. ,  15. ,  92. ,  13. ,  27. ,   2. ,
         25. ],
       [  1. ,   5. ,   5. ,   8. ,  20. ,  92. ,  16. ,  38. ,   1. ,
        300. ],
       [  1. ,  20. ,  65. ,   4. ,  12. ,  98. ,  21. ,   0. ,   1.4,
        120. ]])

In [ ]:
X_opt = X[:, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]
X_opt = X_opt.astype(np.float64)
classifier_OLS = sm.OLS(endog = y, exog = X_opt).fit()
print(classifier_OLS.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.413
Model:                            OLS   Adj. R-squared:                  0.258
Method:                 Least Squares   F-statistic:                     2.662
Date:                Fri, 25 Jun 2021   Prob (F-statistic):             0.0187
Time:                        18:49:27   Log-Likelihood:                -19.034
No. Observations:                  44   AIC:                             58.07
Df Residuals:                      34   BIC:                             75.91
Df Model:                           9                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -1.2684      0.845     -1.501      0.1

In [ ]:
X[0][6]

40.0

In [ ]:
#NO FG
X_opt = X[:, [0, 2, 3, 4, 5, 6, 7, 8, 9]]
X_opt = X_opt.astype(np.float64)
classifier_OLS = sm.OLS(endog = y, exog = X_opt).fit()
print(classifier_OLS.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.412
Model:                            OLS   Adj. R-squared:                  0.278
Method:                 Least Squares   F-statistic:                     3.066
Date:                Fri, 25 Jun 2021   Prob (F-statistic):             0.0100
Time:                        18:51:26   Log-Likelihood:                -19.083
No. Observations:                  44   AIC:                             56.17
Df Residuals:                      35   BIC:                             72.22
Df Model:                           8                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -1.2725      0.833     -1.527      0.1

In [ ]:
#NO IR
X_opt = X[:, [0, 2, 3, 4, 5, 7, 8, 9]]
X_opt = X_opt.astype(np.float64)
classifier_OLS = sm.OLS(endog = y, exog = X_opt).fit()
print(classifier_OLS.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.410
Model:                            OLS   Adj. R-squared:                  0.295
Method:                 Least Squares   F-statistic:                     3.572
Date:                Fri, 25 Jun 2021   Prob (F-statistic):            0.00511
Time:                        18:54:53   Log-Likelihood:                -19.166
No. Observations:                  44   AIC:                             54.33
Df Residuals:                      36   BIC:                             68.61
Df Model:                           7                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -1.1284      0.724     -1.558      0.1

In [ ]:
print(X[0][3])

15.0


In [ ]:
#NO QUALITY FUNDS
X_opt = X[:, [0, 2, 4, 5, 7, 8, 9]]
X_opt = X_opt.astype(np.float64)
classifier_OLS = sm.OLS(endog = y, exog = X_opt).fit()
print(classifier_OLS.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.405
Model:                            OLS   Adj. R-squared:                  0.308
Method:                 Least Squares   F-statistic:                     4.189
Date:                Fri, 25 Jun 2021   Prob (F-statistic):            0.00260
Time:                        18:57:58   Log-Likelihood:                -19.363
No. Observations:                  44   AIC:                             52.73
Df Residuals:                      37   BIC:                             65.22
Df Model:                           6                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -1.2240      0.698     -1.754      0.0

In [ ]:
print(X[0][7])

28.0


In [ ]:
#NO ROE
X_opt = X[:, [0, 2, 4, 5, 8, 9]]
X_opt = X_opt.astype(np.float64)
classifier_OLS = sm.OLS(endog = y, exog = X_opt).fit()
print(classifier_OLS.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.398
Model:                            OLS   Adj. R-squared:                  0.319
Method:                 Least Squares   F-statistic:                     5.026
Date:                Fri, 25 Jun 2021   Prob (F-statistic):            0.00125
Time:                        18:58:42   Log-Likelihood:                -19.601
No. Observations:                  44   AIC:                             51.20
Df Residuals:                      38   BIC:                             61.91
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -1.3933      0.640     -2.178      0.0

In [ ]:
print(X[0][8])

2.4


In [ ]:
#NO U/D
X_opt = X[:, [0, 2, 4, 5, 9]]
X_opt = X_opt.astype(np.float64)
classifier_OLS = sm.OLS(endog = y, exog = X_opt).fit()
print(classifier_OLS.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.365
Model:                            OLS   Adj. R-squared:                  0.300
Method:                 Least Squares   F-statistic:                     5.598
Date:                Fri, 25 Jun 2021   Prob (F-statistic):            0.00117
Time:                        18:59:27   Log-Likelihood:                -20.787
No. Observations:                  44   AIC:                             51.57
Df Residuals:                      39   BIC:                             60.49
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -1.3258      0.647     -2.049      0.0

In [ ]:
#**BEST FEATURES: EG, WEEKS, RS, VOL B.O.

In [ ]:
#**GOOD FEATURES: EG, WEEKS, U/D, VOL B.O.

In [ ]:
#NO VOL B.O.
X_opt = X[:, [0, 2, 4, 5]]
X_opt = X_opt.astype(np.float64)
classifier_OLS = sm.OLS(endog = y, exog = X_opt).fit()
print(classifier_OLS.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.301
Model:                            OLS   Adj. R-squared:                  0.249
Method:                 Least Squares   F-statistic:                     5.741
Date:                Fri, 25 Jun 2021   Prob (F-statistic):            0.00230
Time:                        19:02:40   Log-Likelihood:                -22.890
No. Observations:                  44   AIC:                             53.78
Df Residuals:                      40   BIC:                             60.92
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -1.4648      0.666     -2.199      0.0